### ISSUE TITLE
Update all Ribbon buttons to have descriptions

### ISSUE THREAD

**Issue by byronwall** [byronwall/bUTL#15]
There are a couple that are missing valuable information about what they do and what needs to be selected/chosen.

Known ones:
- Time series option for charts

**Comment by byronwall** [comment]
It would also be good if this text was somehow standardized across the add-in to include the same information for all options.

**Comment by RaymondWise** [comment]
What utility are you using for UI customization?

**Comment by byronwall** [comment]
I use [Andy Pope's Ribbon X Visual Designer](http://www.andypope.info/vba/ribboneditor.htm).  It's by far the most robust Ribbon editor I have used.  It does an excellent job adding and editing items, making you aware of all the options you can set.  I have found only a couple times where it is buggy or crashes.  I also like that it auto generates the callback names.  It does not update the VBA file with them, but it's a simple copy paste to get it all working.  Definitely beats editing the XML by hand.

When I actually do "serious" Ribbon editing (e.g. add several new buttons and rearrange things), I like to keep 2 instances of Excel open so that I can test the new Ribbon without exiting the editor.  It works something like:
- Enable the bUTL add-in for Excel so that it automatically opens when you open Excel (this is my default anyways).  Exit.
- Open the first Excel instance, so that the add-in is visible.  Then, go to the add-ins menus and uncheck bUTL so that it unloads.  Then you can use the Ribbon Editor in that instance to edit bUTL and save changes to the Ribbon.  The editor will overwrite the bUTL.xlam file.  Don't close Excel.
- When you want to test the changes, open a second Excel instance.  It will load the new bUTL file since it still does the autoload (that setting won't change until you close the first instance).  After testing, close the 2nd instance and make more changes in the first.

Slightly complicated, but I've found that works much better than the preview setting.
