### ISSUE TITLE
Improve Selection shifter/offsetter

### ISSUE THREAD

**Issue by byronwall** [byronwall/bUTL#24]
There is a whole interface on the Ribbon for shifting the `Selection` a given number of rows/columns.  This would probably be much better off with a quick keyboard shortcut that shifts the `Selection`.  The interface as it sits is not that useful.  I have actually never used it.

![image](https://cloud.githubusercontent.com/assets/495404/9012402/b6a77d12-3771-11e5-998d-81745db099b6.png)

Decent shortcuts would be CTRL+ALT+{ARROW} to move the `Selection` around.  This has the downside of being the same shortcut used to flip the monitor around.  Not sure if that takes precendence; I disable the monitor flipping stuff.  Another option would be CTRL+ALT+SHIFT+{ARROW} which is not commonly used (I don't think) but involves a lot of keys at once.

Relevant code:

``` vba
Sub SetHotKeys()
    'this would go into an onload for the Ribbon.

    Application.OnKey "^%{RIGHT}", "OffsetRight"

End Sub

Sub OffsetRight()

    Selection.Offset(, 1).Select

End Sub
```

**Comment by RaymondWise** [comment]
For me, it shifts the selection, but not the contents of the cells that were selected. Is that how it was intended?

**Comment by byronwall** [comment]
Yea.  It is supposed to just shift the selection.  It was supposed to help in a case where you some funky selection and just wanted to go over one column to delete the cells next door (or something similar).

Although moving the range might be a more useful thing.  Maybe CTRL+ALT moves selection and CTRL+ALT+SHIFT moves the actual contents.  It gets into the same discussion about how to update formulas when doing that, but it might be useful in a number of cases that are not problematic.  Any thoughts on that?

**Comment by byronwall** [comment]
Like I said, I have never actually used this one because it is not that convenient.  Maybe it is not a useful feature regardless of how accessible it is.  For some reason I like the idea of moving the `Selection` though.  It just seems like something that should be possible.

I am looking at the Ribbon now and thinking of how to organize things better to make room for all the features that don't have space in the Ribbon yet.

**Comment by RaymondWise** [comment]
Well, currently it's impossible to move a selection to anywhere else without making a new selection - so the feature does have some merit in creating functionality.

**Comment by byronwall** [comment]
Alright, I'll wire this one up for the CTRL+ALT shortcuts for now to move the `Selection`.  I'll test that with the monitor shortcuts to make sure this doesn't create a headache for people.

If that works nicely, we can take a look at adding in the ability to move ranges around with the keyboard as well.

I will also remove the textboxes and such from the Ribbon.  This will be keyboard only if it exists.

**Comment by byronwall** [comment]
Got this bit added in.  Cleans up the Ribbon nicely to remove that chunk of boxes.

I confirmed at work that this will **not** play nice with the Intel monitor shortcuts <kbd>CTRL+ALT+{ARROW}</kbd>.  I personally disable those because I never need to rotate the monitor around.  If this is a conflict, let me know.

**Comment by RaymondWise** [comment]
Those are easy enough to disable, but it's too bad that can't be built in when installing the add-in (or give an option to the user on what they want to do).

**Comment by byronwall** [comment]
The add-in could probably hook into some Win32 API and override or maybe disable the monitor shortcuts.  Not sure how easy it is to revert those though when the add-in is closed.  I also start to get a little nervous when the add-in is using those APIs and going into unexpected places.  The user might wonder what the add-in is doing with those API calls.

**Comment by byronwall** [comment]
I'll call this implemented for now.  If the keyboard shortcut becomes an issue, we can open a new issue to address it.  I actually used this the other day to move a selection over.
