### ISSUE TITLE
Add bUTL.xlam to the gitignore file, create release

### ISSUE THREAD

**Issue by byronwall** [byronwall/bUTL#27]
I have hinted at this, but think soon might be a good time to do this.  If the main add-in is added to the `.gitignore` file, then it will motivate rebuilding the `xlam` from the source files on a checkout or branch change.  Your directory will keep whatever `xlam` file you had last, but this will prevent the `xlam` from being out of sync with the source files.  

Technically, the binary version of the VBA stuff is sitting inside the `package` folder, but the xlam script deletes every module and form from the add-in before adding the fresh stuff from `src`.  I think that will be sufficient.

This will also motivate creating a release which can hold the binary xlam that is "final".
- [x] Add the bUTL.xlam file to the ignore
- [x] Create a milestone for the beta release
- [x] Add an any issues to the beta milestone
- [x] Knock out all those issues
- [x] Create a Release for the beta version, add description and binary
- [x] Clarify the contributing section of the README to add the creation step as **mandatory**

**Comment by byronwall** [comment]
I am just playing with issues and the task list in here.  (These are real tasks though).

(Tasks moved to main issue so that the progress shows up in the issue summary... more testing)

**Comment by RaymondWise** [comment]
So you're looking to only sync up the `.vba` and `.frm` files that change, while using the stuff in `scripts`? Then exclude the xlam from git unless it's a release. **I agree**.

Right now all the work I do is in the xlam as I don't have this added as an add-in. I need to use the immediate window to `thisworkbook.save` to save my changes, but I export those out to the `code` folder and sync those. It's a convoluted process, but it might need to be documented for anyone that doesn't have permission to add add-ins, but they want to contribute.

**Comment by byronwall** [comment]
Regarding saving, you can save the xlam file by hitting Save or CTRL+S in the VBA Editor as long as some part of the add-in has focus.  The window title will say `bUTL` if it has focus.  Might be easier than using the immediate window.

Regarding the release, I will use [this form](https://github.com/byronwall/bUTL/releases/new) to create the release and add the xlam file in the binaries section.  I won't ever commit the binary to the repo.

**Comment by byronwall** [comment]
I think I nabbed all of the files that were sporadically changing (various xml files in the `package`) along with the binaries (butl.xlam and vbaProject.bin) and added them to gitignore.  I then went through and [removed them from the index](http://stackoverflow.com/questions/1139762/ignore-files-that-have-already-been-committed-to-a-git-repository?lq=1) which is supposed to make them untracked.

This either fixes things and puts us in a good spot to work only from source files, or I broke it.  Let me know which result looks likely to you.  The only stray file I have problems with is the `../[Content_Types].xml` and I think it might be related to those brackets.

I will go ahead and create the "Release" for the current version of bUTL.xlam to advance this.

**Comment by byronwall** [comment]
I definitely broke it.  I reverted all of those commits (via more commits) and redid the gitignore just for butl.xlam.  It needs all of those other files in the package folder to create the xlam.  Ignoring and removing them created a xlam file that was corrupt.  At this point, things look good to go.

**Comment by byronwall** [comment]
Done.  The beta Release is out there.  Time to start thinking about additional features to support, Ribbon organization and adding buttons for code which does not have them, improving the help, etc.

https://github.com/byronwall/bUTL/releases/tag/v0.1.0-beta
