### ISSUE TITLE
form_newCommands.VBA button5 calls non-existing function

### ISSUE THREAD

**Issue by RaymondWise** [byronwall/bUTL#30]
Private Sub CommandButton5_Click()
    '###This function/sub doesn't exist
    DownloadFromSheet
End Sub

**Comment by byronwall** [comment]
This can just be removed (button and code-behind for the `Click`).  

The `New Features` form existed like a purgatory for new code.  I did not want to trip up users with _really_ experimental features, but I also wanted to be able to call things without having to open the VBE and track them down.  That form was the solution.  It also makes it possible to add new features without editing the Ribbon (which is not hard but somewhat tedious).

We should probably give some thought to whether or not that form exists for much longer.  Maybe there should be a flag in the settings for `Show Developmental Features`?  That flag would then determine whether or not to allow the form to load and whether or not to enable/show the `New Features` button on the Ribbon.

There is a practical reason for having that form, but it is also a bit of a shame to have a relatively polished add-in with a Ribbon interface and then that goofy form full of buttons.
