### ISSUE TITLE
Pie chart fixing?

### ISSUE THREAD

**Issue by RaymondWise** [byronwall/bUTL#41]
I'm no good working with charts and looked through the code in bUTL in reference to this question on SU - http://superuser.com/questions/995587/programmatically-rotate-a-pie-chart-to-fix-the-labels 

Thought you might have a solution.

**Comment by byronwall** [comment]
I looked at this briefly but could not find a clean way to get the size and
position of the pie slice.  Excel seems to do some rearranging of the
slices depending on their relative sizes so relying on Series order and the
value of the data point is not reliable.  The data point has a Top/Left and
Height/Width, but it looks like that applies to bounding box of the slice?
If that information is available, the part about rotating the pie chart
would be doable.  It's simple enough to calculate a "density" of small
slices which could then be oriented into a corner.  The second part about
optimal positioning of labels is much more difficult.  There are some heavy
duty algorithms out there to position labels while drawing other types of
diagrams, but I think in general those are all optimized to the application
at hand.  I doubt there's a simple approach that will best the "Best Fit"
option provided by Excel.

Ultimately, I have typically avoided pie charts so the bUTL code is thin on
that front.  I know there is something of a wider debate there.  I have
always found a stacked bar/column chart to be sufficient when comparing
relative amounts.
