### ISSUE TITLE
Function Download_File doesn't seem to return a value

### ISSUE THREAD

**Issue by RaymondWise** [byronwall/bUTL#55]
Functions should be used to return something whereas subs should be used to do something. The Function Download_File does not appear to return a value and may be better as a sub.

**Comment by byronwall** [comment]
I agree that if there is no return then then it should be a `Sub`.  Sometimes it's easier to create a `Function` that _might_ return something than a `Sub` that cannot.

**Comment by RaymondWise** [comment]
If you prefer the function, go ahead and close this as non-issue. It doesn't bother me, just thought I'd point it out since I saw it.
